---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: portfolio/index.md
  label: Homepage
  templates:
  - settings
- type: directory
  path: portfolio/works
  label: Works
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: portfolio/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - projects
- type: directory
  path: portfolio/projects2
  label: Projects2
  create: all
  match: "**/*"
  templates:
  - projects2
- type: directory
  path: portfolio/projects3
  label: Projects3
  create: all
  match: "**/*"
  templates:
  - projects3
- type: directory
  path: portfolio/projects4
  label: Projects4
  create: all
  match: "**/*"
  templates:
  - projects4
- type: directory
  path: portfolio/journal
  label: Journal
  create: all
  match: "**/[!index]*"
  templates:
  - journal
- type: heading
  label: Data
- type: document
  path: portfolio/config.json
  label: Site Config
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: portfolio/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
